{% set name = "glasbey" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 44b9357dd6cba9d76ab6d3e2fe36d4f2ebd4abfe1456f4de959b7ed8935f504f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - pip
  run:
    - python >=3.9
    - numpy >=1.22
    - numba >=0.56
    - matplotlib-base >=3.5
    - colorspacious

test:
  imports:
    - glasbey
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/lmcinnes/glasbey
  summary: Algorithmically generate categorical colour palettes for Python
  description: |
    The glasbey library allows for the algorithmic creation of colour palettes designed for 
    use with categorical data using techniques from the paper Colour Displays for Categorical Images 
    by Glasbey, Heijden, Toh and Gray. You don't need to worry about the technical details 
    however -- the glasbey library is easy to use.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://glasbey.readthedocs.io/
  dev_url: https://github.com/lmcinnes/glasbey

extra:
  recipe-maintainers:
    - lmcinnes
