{% set python_min = "3.10" %}
{% set name = "glasbey" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8f2c26cc7bb5ae2b8cee7c9c93b28d0edabf5e617a0f152c7519fa981ec79cda

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.22
    - numba >=0.56
    - matplotlib-base >=3.5
    - colorspacious
    - scikit-learn

test:
  imports:
    - glasbey
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/lmcinnes/glasbey
  summary: Algorithmically generate categorical colour palettes for Python
  description: |
    The glasbey library allows for the algorithmic creation of colour palettes designed for 
    use with categorical data using techniques from the paper Colour Displays for Categorical Images 
    by Glasbey, Heijden, Toh and Gray. You don't need to worry about the technical details 
    however -- the glasbey library is easy to use.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://glasbey.readthedocs.io/
  dev_url: https://github.com/lmcinnes/glasbey

extra:
  recipe-maintainers:
    - lmcinnes
